### ISSUE TITLE
stsdas.tables needed for mscfinder

### ISSUE THREAD

**Issue by joshwalawender** [iraf-community/mscred#7]
Having just discovered this community version of IRAF (yay!), I'm trying to reproduce a workflow from a number of years ago reducing some data with `mscred`.  In that workflow, I used `mscfinder.msctpeak` to interactively generate the initial WCS solution which could be applied to all files and then refined automatically.

It looks like `mscfinder` depends on `tables` and I see that `tables` is not supported:

```
ecl> mscred
      ccdhedit       irmpupil       msccmd         mscgetcatalog  mscpupil       mscstack       rmfringe
      ccdlist        mimpars@       mscctran       mscimage       mscrfits       mscstat        rmpupil
      ccdproc        mkmsc          mscdisplay     mscimatch      mscselect      msctoshort     setinstrument
      combine        mscagetcat     mscexamine     mscjoin        mscsetwcs      msctvmark      sflatcombine
      darkcombine    mscarith       mscfinder      mscmedian      mscshutcor     mscwcs         xtalkcor
      flatcombine    mscblkavg      mscfindgain    mscotfflat     mscskysub      mscwfits       xtcoeff
      irmfringe      msccmatch      mscfocus       mscpixarea     mscsplit       msczero        zerocombine

mscred> mscfinder
ERROR: task `tables' not found
     called as: `cl ()'
```

Does anyone have a workaround for this or is `mscfinder` effectively dead?

**Comment by olebole** [comment]
The **tables.ttools** package is part of STSDAS, which is not ported to 64 bit yet.Parts of it are however now taken to main IRAF as the [**utilities.nttools**](https://iraf.readthedocs.io/en/latest/tasks/utilities/nttools/index.html) package. You could try out whether this works and adjust the package startup in https://github.com/iraf-community/iraf-mscred/blob/ce5fef9e379a4a821ff856e379029bde146c3595/src/mscfinder/mscfinder.cl#L4-L5 and https://github.com/iraf-community/iraf-mscred/blob/ce5fef9e379a4a821ff856e379029bde146c3595/src/mscfinder/mktpeaktab.cl#L22-L23 accordingly.
If you get it work this way, please consider providing a pull request here so that others can benefit as well.
